FROM debian:buster
MAINTAINER "Matt Hart" <matt@mattface.org>

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install bc bsdmainutils make bison flex ccache wget libelf-dev tar python2.7 python-requests python-pyelftools libssl-dev lzop

#whoami doesnt work in docker
RUN echo "#!/bin/bash\necho root\n" > /usr/bin/whoami
